### ISSUE TITLE
Cannot find module 'xxx/srv

### ISSUE THREAD

**Issue by mathieutu** [mathieutu/serve-my-app#13]
```bash
$ serve-my-app --src=.vuepress/dist
(node:33998) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/mathieutu/Projects/mathieutu.dev/srv'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at isTypescriptFile (/Users/mathieutu/Projects/mathieutu.dev/node_modules/serve-my-app/dist/utils/paths.js:29:49)
    at Object.exports.load (/Users/mathieutu/Projects/mathieutu.dev/node_modules/serve-my-app/dist/utils/paths.js:34:9)
    at Object.<anonymous> (/Users/mathieutu/Projects/mathieutu.dev/node_modules/serve-my-app/dist/run.js:27:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mathieutu/Projects/mathieutu.dev/node_modules/serve-my-app/dist/run.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
(node:33998) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33998) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mathieutu** [comment]
```ts
export const load = (path: string) => {
  const empty = () => {}

  if (!moduleIsAvailable(path)) {
    return empty
  }


  if (isTypescriptFile(path)) {
    require('ts-node').register(getTypescriptConfig(path))
  }
  
  const module = require(path)
  return module.default || module || empty
}
```
at https://github.com/mathieutu/serve-my-app/blob/master/src/utils/paths.ts#L39
